# app_lucky_number:
#    path: /
#    controller: App\Controller\LuckyController::number

admin:
  type: rest
  resource: App\Controller\AdminController
  prefix: api

api_login_check:
  path: /api/login_check
